/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package major_project;

import java.util.List;

import javafx.application.Application;
import javafx.application.Platform;
import javafx.stage.Stage;
import major_project.model.DatabaseHandler;
import major_project.model.Model;
import major_project.presenter.Presenter;
import major_project.view.AppWindow;

public class App extends Application {

    @Override
    public void start(Stage primaryStage) throws Exception {
        List<String> args = getParameters().getRaw();
        if (args.size() < 2) {
            System.out.println("command line arguments missing");
            Platform.exit();
        }
        else {
            Model model = new Model(args.get(0).equals("online"), args.get(1).equals("online"), new DatabaseHandler());
            AppWindow view = new AppWindow(primaryStage);
            Presenter presenter = new Presenter(model, view);
            
            primaryStage.setScene(view.getScene());
            presenter.start();
        }
    }

    public static void main(String[] args) {
        App.launch(args);
    }
}
