/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package major_project;

import org.junit.jupiter.api.Test;

import major_project.model.Currency;

import static org.junit.jupiter.api.Assertions.*;



class CurrencyTest {
    @Test void equalTest() {
        Currency c = new Currency("name", "symbol", 12);
        Currency c2 = new Currency("name", "symbol", 12);
        Currency c3 = new Currency("not_name", "symbol", 12);
        Currency c4 = new Currency("name", "not_symbol", 12);
        Currency c5 = new Currency("name", "symbol", 13);
        assertTrue(c.equals(c2));
        assertFalse(c.equals(c3));
        assertFalse(c.equals(c4));
        assertFalse(c.equals(c5));
        
    }
}
